### ISSUE TITLE
Updating a model does not trigger collection PR

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/collection-bioimage-io#303]
![image](https://user-images.githubusercontent.com/4263537/155792323-13918c42-c0bd-4885-a384-2623674bc0b1.png)

**Comment by FynnBe** [comment]
should be fixed by https://github.com/bioimage-io/bioimage.io/commit/4ec005dd1456dd4dfbc581f880f984917b8c9384
please try again in a little while

**Comment by constantinpape** [comment]
The update is still not triggered: now there isn't an error message after the upload any more
![image](https://user-images.githubusercontent.com/4263537/156145958-406eed3e-705c-4b00-91b4-1d0a97a31c36.png)
But the PR is not triggered in https://github.com/bioimage-io/collection-bioimage-io/pulls

**Comment by oeway** [comment]
This is because the change of the workflow name as @FynnBe already try to fix, however, changing that in the bioimage.io repo won't be automatically deployed to netlify, we need to either redeploy the netlify, or simply change the workflow name to `auto_update_main.yaml`. For now, I would rather change the workflow name.

**Comment by FynnBe** [comment]
what's so hard about redeploying the website? And how are the changes that I made for the id links deployed, but the name change is not?

**Comment by constantinpape** [comment]
Sorry, I probably miss some context about the details, but is there a reason why we have changed the wf name and can we just fix it by changing the name back or will this cause other issues?

**Comment by FynnBe** [comment]
I can of course change it back, but for the time being we can also simply trigger the workflow a few times manually or increase the cron job so we pick up on new resources timely... 
It should not take too long to redeploy the website I suppose. @oeway maybe you can document how the website deployment works, so we can do this more easily in the future?

**Comment by constantinpape** [comment]
> @oeway maybe you can document how the website deployment works, so we can do this more easily in the future?

Yeah, it would be good to document this!

**Comment by oeway** [comment]
> what's so hard about redeploying the website? And how are the changes that I made for the id links deployed, but the name change is not?

It's not the website, it called netlify functions. It has a different development workflow as the website and is entirely manual at the moment. I need to setup the environment locally and get some credentials. I do have limited bandwidth at the moment, but it's not about that. I am thinking that the overall strategy we take should be more conservative to make sure we don't break the website. The thing is, upgrading the netlify function should not affect other stuff in principle, but without through testing or analysis I cannot say for sure. While what I know is that if we change the name back, everything should be fine as before. Unless you have a strong reason to not use the old name, the best strategy for me is to change the name back, for the sake of availability of the website and not introducing new issues. 

In general, I am sure the new changes are good and necessary, but we tend to underestimate the issues that one simple change can cause. And it's not a good idea to make the website losing these features for days (or we working around the clock to fix them). Besides more testing before merging, we should also split the changes into smaller PR so we can easily revert immediately to avoid break the website for too long.


> Sorry, I probably miss some context about the details, but is there a reason why we have changed the wf name and can we just fix it by changing the name back or will this cause other issues?

Yes, I think changing back should fix the issue (and potentially avoid propagating the issue further to other parts).

> Yeah, it would be good to document this!

Agreed, will do when I am back to this.

**Comment by constantinpape** [comment]
> It's not the website, it called netlify functions. It has a different development workflow as the website and is entirely manual at the moment. I need to setup the environment locally and get some credentials. I do have limited bandwidth at the moment, but it's not about that. I am thinking that the overall strategy we take should be more conservative to make sure we don't break the website. The thing is, upgrading the netlify function should not affect other stuff in principle, but without through testing or analysis I cannot say for sure. While what I know is that if we change the name back, everything should be fine as before. Unless you have a strong reason to not use the old name, the best strategy for me is to change the name back, for the sake of availability of the website and not introducing new issues.
> 
> In general, I am sure the new changes are good and necessary, but we tend to underestimate the issues that one simple change can cause. And it's not a good idea to make the website losing these features for days (or we working around the clock to fix them). Besides more testing before merging, we should also split the changes into smaller PR so we can easily revert immediately to avoid break the website for too long.

Thanks for clarifying @oeway. I agree that we should aim for more incremental changes and smaller PRs. 
So let's change the workflow name back, or is there anything crucial depending on this on the backend part, @FynnBe?

> > Yeah, it would be good to document this!
> 
> Agreed, will do when I am back to this.

Ok, that would be great, since there will certainly be the need to redeploy this at some point.

**Comment by FynnBe** [comment]
> So let's change the workflow name back, or is there anything crucial depending on this on the backend part, @FynnBe?

sure, I'll change the file name then...

**Comment by constantinpape** [comment]
Now we're back to this issue:
![image](https://user-images.githubusercontent.com/4263537/156239017-40f5d67a-1be4-498e-aef7-339c909e66cb.png)

**Comment by FynnBe** [comment]
I don't understand how the website is updated by pushes to the bioimage.io repository, but at the same time also is not...

**Comment by FynnBe** [comment]
hope this has fixed it: https://github.com/bioimage-io/bioimage.io/pull/247

**Comment by constantinpape** [comment]
It's working now
