### ISSUE TITLE
downloader does not download the updated version of the model

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/collection-bioimage-io#590]
Hi there,

Related to this issue: https://github.com/bioimage-io/collection-bioimage-io/issues/571

The model is updated and rdf file in zenodo updated successfully. However, the downloader downloads the old version of the rdf file. Any idea?

**Comment by FynnBe** [comment]
the latest known version was still version 3 from last week.

I merged the PR with version 5 eight minutes ago: #591

In a few minutes this version 5 should also be available on bioimage.io

**Comment by esgomezm** [comment]
The problem remains the same. The downloader seems to download an old version of the model.

**Comment by FynnBe** [comment]
I'll investigate...

**Comment by esgomezm** [comment]
Cool thanks. Once solved, will the model be updated automatically or do we need to run again anything?

**Comment by FynnBe** [comment]
it had to run only once:, version 5 is online: https://bioimage.io/#/?tags=placid-llama&id=10.5281%2Fzenodo.7261974

**Comment by esgomezm** [comment]
It's working!!! Lovely, thank you 👯
